include: package:very_good_analysis/analysis_options.yaml

linter:

  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    inference_failure_on_generic_invocation: false
    avoid_dynamic_calls: false
