name: color_picker
description: 컬러피커

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.3
  flutter_colorpicker: ^1.0.3
  image_picker: ^0.8.5+3
  image: ^3.2.0
  logger: ^1.1.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.0.0
  share_plus: ^4.0.10
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
