name: color_picker
description: 컬러피커

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.1
  flutter_colorpicker: ^1.0.3
  image_picker: ^0.8.4+11
  image: ^3.1.3
  logger: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - images/
